version: '3.8'
services:
 frontend:
    image: sanghrakshit/mtx_frontend
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "4000:4000"
 backend:
    image: sanghrakshit/mtx_backend 
    container_name: backend_app
    ports:
      - "3000:3000"